dbUserPasswords:
  dbuserPassword: 2OZDITdKIMha4jW

databases:
  mosip_toolkit:
    enabled: false
  
  mosip_master:
    enabled: false
  
  mosip_audit:
    enabled: false
  
  mosip_keymgr:
    enabled: false
  
  mosip_kernel:
    enabled: false
  
  mosip_idmap:
    enabled: false
  
  mosip_prereg:
    enabled: false
  
  mosip_idrepo:
    enabled: false
  
  mosip_ida:
    enabled: false
  
  mosip_credential:
    enabled: false
  
  mosip_regprc:
    enabled: false
  
  mosip_regdevice:
    enabled: false
  
  mosip_authdevice:
    enabled: false
  
  mosip_pms:
    enabled: false
  
  mosip_hotlist:
    enabled: false
  
  mosip_resident:
    enabled: false
  
  mosip_digitalcard:
    enabled: false

  mosip_mockidentitysystem:
    enabled: false
  
  mosip_esignet:
    enabled: true
    host: "rdsstack-databaseb269d8bb-wtjrn0lxj2sw.cluster-cveklit2rj4m.ap-south-1.rds.amazonaws.com"
    port: 5432
    su:
      user: postgres
      secret:
        name: postgres-postgresql
        key: password
    dml: 1
    repoUrl: https://github.com/dpgonaws/esignet.git #https://github.com/mosip/esignet.git
    branch: aws-v01
